In [1]:
import numpy as np
import matplotlib.pyplot as plt



In [174]:
def train_perceptron(X, y, eta = 1, epochs = 20):
  #theta = np.zeros(len(X[0])+1)
  #theta = [1,-1,1]
  theta = np.random.randint(-10, 11, size=3)
  print('theta_inicial', theta)
  m = 0
  X = np.insert(X, 0, 1, axis=1)
  print(X)
  for t in range(epochs):
    for i, x in enumerate(X):
      if y[i]*(np.dot(X[i],theta)) <= 0.0:
        theta = theta + y[i]*X[i]
        m +=1
     
  return theta, m

In [ ]:
for i in range(100):
  theta, m = train_perceptron(X,y, eta =1, epochs = 20)
  print(theta)
  print(m)
  if m == 1:
    break

In [171]:
X=np.array([[-4,2],[-2,1],[-1, -1],[2,2],[1,-2]])
y = np.array([1,1,-1,-1, -1])
theta, m = train_perceptron(X,y)

print(theta)
print('m',m)
plt.scatter(X[:,0],X[:,1], c = y)
line_x = np.linspace(-5, 5, 100)
line_y = -theta[1]/theta[2] * line_x - theta[0]/theta[2]

# Plot the line
plt.plot(line_x, line_y, color='red')
plt.show()

theta_inicial [1, -1, 1]
[[ 1 -4  2]
 [ 1 -2  1]
 [ 1 -1 -1]
 [ 1  2  2]
 [ 1  1 -2]]
[-2 -1  1]
m 3


In [159]:
theta, m = train_perceptron(X,y)
print(theta,m)

theta_inicial [1, -2, 2]
[[ 1 -4  2]
 [ 1 -2  1]
 [ 1 -1 -1]
 [ 1  2  2]
 [ 1  1 -2]]
[-2 -2  2] 3


In [5]:
def train_perceptron_origin(X, y, eta = 1, epochs = 20):
  theta = np.zeros(len(X[0])) #without a theta_0 = 0 (origin)
  print('theta_inicial', theta)
  m = 0  
  print(X)
  for t in range(epochs):
    for i, x in enumerate(X):
      if y[i]*(np.dot(X[i],theta)) <= 0.0:
        theta = theta + y[i]*X[i]
        print('theta_cambiado:', theta)
        m +=1
        print('mistake', m)
  return theta, m

In [6]:
X=np.array([[-1,0],[0,1]])
y = np.array([1,1])


#X=np.array([[1,0],[-1,-1],[-1, 10]])
#y = np.array([-1,1,1])


In [7]:
w, m = train_perceptron_origin(X,y)
print(w)
print(m)

theta_inicial [0. 0.]
[[-1  0]
 [ 0  1]]
theta_cambiado: [-1.  0.]
mistake 1
theta_cambiado: [-1.  1.]
mistake 2
[-1.  1.]
2
