<a href="https://colab.research.google.com/github/JavierPachas/ml-projects/blob/main/perceptron_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [19]:
points = np.array([[-1, -1], [1, 0], [-1, 1.5]])
labels = np.array([1, -1, 1])

T = 30
theta = np.array([0, 0])
#theta_0 = 0
n_errors = 0

for t in range(T):
  for i in range(3):
    if labels[i]*np.sum(theta*points[i]) <= 0:
      theta = theta + labels[i]*points[i]
      #theta_0 = theta_0 + label[i]
      n_errors +=1




In [20]:
theta

array([-2. ,  0.5])

In [21]:
n_errors

2

In [22]:
points = np.array([ [1, 0], [-1, 1.5], [-1, -1]])
labels = np.array([ -1, 1, 1])

T = 30
theta = np.array([0, 0])
#theta_0 = 0
n_errors = 0

for t in range(T):
  for i in range(3):
    if labels[i]*np.sum(theta*points[i]) <= 0:
      theta = theta + labels[i]*points[i]
      #theta_0 = theta_0 + label[i]
      n_errors +=1

In [23]:
theta

array([-1.,  0.])

In [24]:
n_errors

1

In [37]:
points = np.array([ [1, -4, 2], [1, -2, 1], [1, -1, -1], [1, 2, 2], [1,1,-2]])
labels = np.array([ 1, 1, -1, -1, -1])

misclassified = [1, 0, 2, 1, 0]

T = 30
theta = np.array([0, 0, 0])

for t in range(T):
  for i in range(5):
    if labels[i]*np.sum(theta*points[i]) <= 0:
      theta = theta + labels[i]*points[i]


In [38]:
theta

array([-3, -3,  3])

In [35]:
theta = [0, 0, 0]
frecuencias = [1, 0, 2,1, 0]

for i in range(5):
  theta = theta + frecuencias[i]*labels[i]*points[i]

In [36]:
theta

array([-2, -4,  2])